dist: trusty

language: php

php:
  - 7.0
  - 7.1
  - 7.2
  - nightly
  - hhvm
  - hhvm-nightly

matrix:
  allow_failures:
    - php: hhvm
    - php: hhvm-nightly

before_script:
  - sh .travis.sh install

script:
  - sh .travis.sh run-tests
