language: php

php:
  - 7.0
  - 7.1
  - 7.2
  - 7.3
  - 7.4
  - 7.4snapshot
  - master

matrix:
  allow_failures:
    - php: master

before_script:
  - sh .github/workflows/ci.sh install

script:
  - sh .github/workflows/ci.sh run-tests
