dist: trusty

language: php

services:
  - docker

php:
  - 7.0
  - 7.1
  - hhvm
  - nightly

matrix:
  allow_failures:
    - php: nightly

before_script:
  - sh .travis.sh install

script:
  - sh .travis.sh run-tests
