dist: trusty

language: php

services:
  - docker

php:
  - 7.0
  - 7.1
  - hhvm
  - nightly

matrix:
  allow_failures:
    - php: nightly

before_script:
  - curl -sSL https://dl.bintray.com/xp-runners/generic/xp-run-master.sh > xp-run
  - sh .travis.sh install
  - echo test.xar > test.pth

script:
  - sh .travis.sh run-tests
