dist: trusty

language: php

php:
  - 7.0
  - 7.1
  - 7.2
  - 7.3
  - 7.4snapshot
  - nightly

matrix:
  allow_failures:
    - php: nightly

before_script:
  - sh .travis.sh install

script:
  - sh .travis.sh run-tests
