dist: trusty

language: php

php:
  - 7.0
  - 7.1
  - 7.2
  - 7.3
  - nightly

before_script:
  - if [[ $TRAVIS_PHP_VERSION = "hhvm"* ]]; then echo hhvm.hack_compiler_default=false > /etc/hhvm/php.ini; fi
  - sh .travis.sh install

script:
  - sh .travis.sh run-tests
