language: php

services: docker

dist: trusty

php:
  - 7.0
  - 7.1
  - hhvm
  - nightly

matrix:
  allow_failures:
    - php: hhvm
    - php: nightly

before_script:
  - curl -sSL https://dl.bintray.com/xp-runners/generic/xp-run-master.sh > xp-run
  - echo "test.xar" > composer.pth
  - sh .travis.sh install

script:
  - sh .travis.sh run-tests
