build: false  

shallow_clone: true  

cache:
  - .\xp -> appveyor.yml 
  - vendor -> composer.json

init:
  - set PATH=%PATH%;.\xp
  - set COMPOSER_NO_INTERACTION=1
  - set CACHED=0

install:
  - if exist .\xp (set CACHED=1) else (mkdir .\xp)
  - if %CACHED%==0 cd .\xp
  - if %CACHED%==0 curl -fsS -o php.zip https://windows.php.net/downloads/releases/archives/php-8.2.6-nts-Win32-vs16-x64.zip
  - if %CACHED%==0 appveyor DownloadFile https://getcomposer.org/composer.phar
  - if %CACHED%==0 appveyor DownloadFile https://baltocdn.com/xp-framework/xp-runners/distribution/downloads/z/zip/xp-runners_8.6.2.zip -FileName xp.zip
  - if %CACHED%==0 7z x php.zip -y
  - if %CACHED%==0 7z x xp.zip -y
  - if %CACHED%==0 echo extension_dir=%cd%\ext >> php.ini
  - if %CACHED%==0 echo extension=php_com_dotnet.dll >> php.ini
  - if %CACHED%==0 echo extension=php_openssl.dll >> php.ini
  - if %CACHED%==0 echo extension=php_bz2.dll >> php.ini
  - if %CACHED%==0 echo extension=php_sodium.dll >> php.ini
  - if %CACHED%==0 cd ..
  - type .\xp\php.ini

test_script:
  - for /f "skip=1 tokens=1-2" %%a in ('findstr /r /c:"^## " ChangeLog.md') do ( set COMPOSER_ROOT_VERSION=%%b & php .\xp\composer.phar install --prefer-dist & exit /b )
  - echo src/main/php/__xp.php > composer.pth
  - echo vendor/autoload.php >> composer.pth
  - xp -m . xp.test.Runner -r Dots src/test/php
